/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2022-11-14 15:29:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import modelo.*;

public final class PagPrincipal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("modelo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"style.css\"/>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>JSP Page</title>\r\n");
      out.write("    </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    \r\n");
      out.write("    ");
Pc pc1= new Pc("Programmer One",5000); 
      Pc pc2= new Pc("Programmer Two",65000); 
      Pc pc3= new Pc("Gamming One",55000); 
      Pc pc4= new Pc("Gaming Two",73000); 
      
      
      Ram ram1 = new Ram("Fury","USA",8000,8);
      Procesador p1 = new Procesador("Intel I5","USA",30000,5000);
      Gabinete gab1= new Gabinete("TzLight","Arg",10000,"Negro/Led");
      
      pc1.agregarComp(ram1);
      pc1.agregarComp(p1);
      pc1.agregarComp(gab1);
    
    
    
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"logo__container\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <img src=\"img/logo_pag.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"links\">\r\n");
      out.write("            <a href=\"#\">Inicio</a>\r\n");
      out.write("            <a href=\"#\">About us</a>\r\n");
      out.write("            <a href=\"#\">Estadisticas</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"Main\">\r\n");
      out.write("\r\n");
      out.write("        <h1>Bienvenidos a TecnoWorld</h1>\r\n");
      out.write("       <form action=\"\">\r\n");
      out.write("            <div class=\"economicas__container\">\r\n");
      out.write("                <div class=\"programing__economica\">\r\n");
      out.write("                    <h2>Economicas para Programadores</h2>\r\n");
      out.write("                    <div class=\"pc\">\r\n");
      out.write("                        <h3> ");
      out.print( pc1.getNombre());
      out.write(" </h3>\r\n");
      out.write("                        <div class=\"pc__img__container\">\r\n");
      out.write("                            <img src=\"img/epc1.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p>");
      out.print( ram1.toString());
      out.write("</p>\r\n");
      out.write("                        <p>");
      out.print( p1.toString());
      out.write("</p>\r\n");
      out.write("                        <p>");
      out.print( gab1.toString());
      out.write("</p>\r\n");
      out.write("                        <h2 class=\"precio\">$");
      out.print( pc1.calcularTotalPc());
      out.write("</h2>\r\n");
      out.write("                        <input type=\"submit\" value=\"Comprar\" name=\"Compra\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"pc\">\r\n");
      out.write("                        <h3>");
      out.print( pc2.getNombre());
      out.write("</h3>\r\n");
      out.write("                        <div class=\"pc__img__container\">\r\n");
      out.write("                            <img src=\"img/epc2.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p>Ram 8gb</p>\r\n");
      out.write("                        <p>Proc Intel i5 7ma Gen</p>\r\n");
      out.write("                        <p>Gabinete Z</p>\r\n");
      out.write("                        <h2 class=\"precio\">$");
      out.print( pc2.getPrecio());
      out.write("</h2>\r\n");
      out.write("                        <input type=\"submit\" value=\"Comprar\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"gamer__economica\">\r\n");
      out.write("                    <h2>Economicas Gamers</h2>\r\n");
      out.write("                    <div class=\"pc\">\r\n");
      out.write("                        <h3>");
      out.print( pc3.getNombre());
      out.write("</h3>\r\n");
      out.write("                        <div class=\"pc__img__container\">\r\n");
      out.write("                            <img src=\"img/eg1.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p>Ram 8gb</p>\r\n");
      out.write("                        <p>Proc Intel i5 7ma Gen</p>\r\n");
      out.write("                        <p>Gabinete Z</p>\r\n");
      out.write("                        <h2 class=\"precio\">$");
      out.print( pc3.getPrecio());
      out.write("</h2>\r\n");
      out.write("                        <input type=\"submit\" value=\"Comprar\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"pc\">\r\n");
      out.write("                        <h3>");
      out.print( pc4.getNombre());
      out.write("</h3>\r\n");
      out.write("                        <div class=\"pc__img__container\">\r\n");
      out.write("                            <img src=\"img/eg2.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p>Ram 8gb</p>\r\n");
      out.write("                        <p>Proc Intel i5 7ma Gen</p>\r\n");
      out.write("                        <p>Gabinete Z</p>\r\n");
      out.write("                        <h2 class=\"precio\">$");
      out.print( pc4.getPrecio());
      out.write("</h2>\r\n");
      out.write("                        <input type=\"submit\" value=\"Comprar\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
